### ISSUE TITLE
Make google tracker code optional (again).

### ISSUE THREAD

**Issue by jeanmartin** [sporkd/compass-html5-boilerplate#1]
Just wondering why the google_tracker_id check was removed in 0.2.0.
Since the default now is 'UA-XXXXX-X' we could check for this value or empty?
I can take care of this, just wanted to ask if it was intentional.

**Comment by sporkd** [comment]
Yea, it now checks for the tracking code (and api key) in config/google.yml or your env.   I added a helper method that checks in both places for you.
http://github.com/sporkd/compass-html5-boilerplate/blob/master/lib/app/helpers/html5_boilerplate_helper.rb

So for now, if you don't want tracking, just remove the line from your _javascripts.html.haml.  But good point.  Possibly I should make it so if you don't set a tracking code in the yml, it will hide the analytics code block again.

peter

**Comment by jeanmartin** [comment]
nice, thank you :)
