### ISSUE TITLE
haml parse error in standalone install

### ISSUE THREAD

**Issue by bstaats** [sporkd/compass-html5-boilerplate#10]
All my gems are updated. Below is the command + error.

compass create MyBoilerplate -r html5-boilerplate -u html5-boilerplate --javascripts-dir js --css-dir css
directory MyBoilerplate/
   exists MyBoilerplate/.
directory MyBoilerplate/css/
directory MyBoilerplate/js/
directory MyBoilerplate/src/
directory MyBoilerplate/src/partials/
   create MyBoilerplate/config.rb
   create MyBoilerplate/src/style.scss
   create MyBoilerplate/src/handheld.scss
   create MyBoilerplate/src/partials/_base.scss
   create MyBoilerplate/src/partials/_overrides.scss
   create MyBoilerplate/src/partials/_fonts.scss
   create MyBoilerplate/src/partials/_media.scss
   create MyBoilerplate/src/partials/_page.scss
SyntaxError on line ["188"] of /Users/bstaats/.rvm/gems/ruby-1.9.2-p180/gems/haml-3.0.25/lib/haml/engine.rb: /Users/bstaats/.rvm/gems/ruby-1.9.2-p180/gems/html5-boilerplate-0.3.3/lib/../templates/project/index.html.haml:19: syntax error, unexpected ':', expecting ')'
... nil, nil,  :name => "author" :content => "" );_hamlout.push...
...                               ^
Run with --trace to see the full backtrace

**Comment by bstaats** [comment]
Missing a comma after "author". works after adding it.

**Comment by sporkd** [comment]
Thanks for the heads up.  I'll fix this in the next release.
