### ISSUE TITLE
Missing '!' or explicit return in add_class

### ISSUE THREAD

**Issue by cetrasoft** [sporkd/compass-html5-boilerplate#13]
Thanks for your great compass plugin. I recently ran into this while trying to get it all up and running following your instructions (I'm on Rails 3.0.5):

```
undefined method `each_pair' for "ie6 {:class=>\"no-js\", :lang=>\"en\"}":String
Extracted source (around line #3):

1: !!! 5
2: -# http://paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither
3: -ie_html :class => 'no-js', :lang => 'en' do
4:   %head
5:     = render "layouts/head", :stylesheet_partial => "layouts/stylesheets"
6:   
Rails.root: /Users/ryanjafari/Documents/rh/cetrasoft

Application Trace | Framework Trace | Full Trace
app/helpers/html5_boilerplate_helper.rb:6:in `ie_tag'
app/helpers/html5_boilerplate_helper.rb:17:in `ie_html'
app/views/layouts/application.html.haml:3:in `_app_views_layouts_application_html_haml___1196574397641461931_2175933500__872331275792864834'
```

I remedied it by overriding the following method in `html5_boilerplate_helper.rb`. They key change being the `!` on the last line.

``` ruby
def add_class_fix(name, attrs)
      classes = attrs[:class] || ''
      classes.strip!
      classes = ' ' + classes if !classes.blank?
      classes = name + classes
      attrs.merge!(:class => classes)
end
```

Unsure if this is the best medium for this kind of notice, but thought to inform you of my experience.

Thanks again for all your hard work!
Ryan

**Comment by sporkd** [comment]
Not sure what is going on here, but I suspect it's something similar to this issue:
https://github.com/aslakhellesoy/gherkin/issues/76

Maybe check to see if you're including TagHelper anywhere.

Peter

**Comment by cetrasoft** [comment]
Hi Peter,

Thanks for your response. I've checked it out and we are not using TagHelper anywhere in our project.

Best,
Ryan

**Comment by sporkd** [comment]
Yea, I don't have any other ideas.  If you haven't already, try installing it on a fresh project with just the bare minimum gems. Unless other people start having this same problem, I'd say it's something specific to your setup.

**Comment by cetrasoft** [comment]
No worries. I've resolved it anyway as I mentioned above. Just wanted to post in case anyone came across a similar problem. Thanks!
