### ISSUE TITLE
Compile error creating a standalone project

### ISSUE THREAD

**Issue by bartdepotter** [sporkd/compass-html5-boilerplate#14]
Hi,

I got the following error in on index.html.haml.

`SyntaxError on line 19 of /Library/Ruby/Gems/1.8/gems/html5-boilerplate-0.3.3/lib/../templates/project/index.html.haml: compile error
/Library/Ruby/Gems/1.8/gems/html5-boilerplate-0.3.3/lib/../templates/project/index.html.haml:19: syntax error, unexpected ':', expecting ')'
...nil, nil,  :name => "author" :content => "" );_hamlout.push_...`

**Comment by strass** [comment]
Add a , to line 19 in the file and it works

```
mate /Library/Ruby/Gems/1.8/gems/html5-boilerplate-0.3.3/lib/../templates/project/index.html.haml
%meta{ :name => "author", :content => "" }/
```

**Comment by sporkd** [comment]
Thanks.  Fixed.
