### ISSUE TITLE
Error when creating default (non-rails) template from wiki instructions

### ISSUE THREAD

**Issue by dmmalam** [sporkd/compass-html5-boilerplate#15]
Installed v0.3.3  via

> gem install html5-boilerplate 
> using ruby 1.9.2, I have the output from `gem lis`t right at the bottom

ran the below to create a default project using compass

> compass create project -r html5-boilerplate -u html5-boilerplate --javascripts-dir js --css-dir css --trace

directory project/
directory project/css/
directory project/js/
directory project/sass/
directory project/sass/partials/
   create project/config.rb 
   create project/sass/style.scss 
   create project/sass/handheld.scss 
   create project/sass/partials/_base.scss 
   create project/sass/partials/_overrides.scss 
   create project/sass/partials/_fonts.scss 
   create project/sass/partials/_media.scss 
   create project/sass/partials/_page.scss 
SyntaxError on line ["191"] of /Users/dharmesh/.rvm/gems/ruby-1.9.2-p180/gems/haml-3.1.1/lib/haml/engine.rb: /Users/dharmesh/.rvm/gems/ruby-1.9.2-p180/gems/html5-boilerplate-0.3.3/lib/../templates/project/index.html.haml:19: unknown regexp options - javacrpt
/Users/dharmesh/.rvm/gems/ruby-1.9.2-p180/gems/html5-boilerplate-0.3.3/lib/../templates/project/index.html.haml:19: syntax error, unexpected tSTRING_BEG, expecting '}'
... <script type='text/javascript'>\n      //<![CDATA[\n       ...
...                               ^
/Users/dharmesh/.rvm/gems/ruby-1.9.2-p180/gems/html5-boilerplate-0.3.3/lib/../templates/project/index.html.haml:19: syntax error, unexpected tIDENTIFIER, expecting '}'
...ocument.write(\"<script src='js/jquery.min.js'>\x3C/script>...
...                               ^
/Users/dharmesh/.rvm/gems/ruby-1.9.2-p180/gems/html5-boilerplate-0.3.3/lib/../templates/project/index.html.haml:19: syntax error, unexpected tSTRING_BEG, expecting '}'
..."<script src='js/jquery.min.js'>\x3C/script>\")\n      //]]...
...                               ^
/Users/dharmesh/.rvm/gems/ruby-1.9.2-p180/gems/html5-boilerplate-0.3.3/lib/../templates/project/index.html.haml:19: syntax error, unexpected tIDENTIFIER, expecting '}'
... </script>\n    <script src='js/plugins.js?v=1'></script>\n ...
...                               ^
/Users/dharmesh/.rvm/gems/ruby-1.9.2-p180/gems/html5-boilerplate-0.3.3/lib/../templates/project/index.html.haml:19: syntax error, unexpected tIDENTIFIER, expecting '}'
...   <script src='js/plugins.js?v=1'></script>\n    <script sr...
...                               ^
/Users/dharmesh/.rvm/gems/ruby-1.9.2-p180/gems/html5-boilerplate-0.3.3/lib/../templates/project/index.html.haml:19: syntax error, unexpected tSTRING_BEG, expecting '}'
...<script src='js/plugins.js?v=1'></script>\n    <script src='...
...                               ^
/Users/dharmesh/.rvm/gems/ruby-1.9.2-p180/gems/html5-boilerplate-0.3.3/lib/../templates/project/index.html.haml:19: syntax error, unexpected tIDENTIFIER, expecting '}'
...></script>\n    <script src='js/script.js?v=1'></script>\n  ...
...                               ^
/Users/dharmesh/.rvm/gems/ruby-1.9.2-p180/gems/html5-boilerplate-0.3.3/lib/../templates/project/index.html.haml:19: syntax error, unexpected tIDENTIFIER, expecting '}'
...    <script src='js/script.js?v=1'></script>\n    \n    <script type='text/javascript'>\n      //<![CDA...
...                               ^
/Users/dharmesh/.rvm/gems/ruby-1.9.2-p180/gems/html5-boilerplate-0.3.3/lib/../templates/project/index.html.haml:19: syntax error, unexpected tSTRING_BEG, expecting keyword_do or '{' or '('
... <script type='text/javascript'>\n      //<![CDATA[\n       ...
...                               ^
/Users/dharmesh/.rvm/gems/ruby-1.9.2-p180/gems/html5-boilerplate-0.3.3/lib/../templates/project/index.html.haml:19: unterminated string meets end of file
  /Users/dharmesh/.rvm/gems/ruby-1.9.2-p180/gems/haml-3.1.1/lib/haml/engine.rb:191:in `render'
  /Users/dharmesh/.rvm/gems/ruby-1.9.2-p180/gems/compass-0.11.1/lib/compass/installers/base.rb:160:in`install_html'
  /Users/dharmesh/.rvm/gems/ruby-1.9.2-p180/gems/compass-0.11.1/lib/compass/installers/manifest_installer.rb:39:in `block in install'
  /Users/dharmesh/.rvm/gems/ruby-1.9.2-p180/gems/compass-0.11.1/lib/compass/installers/manifest.rb:112:in`block in each'
  /Users/dharmesh/.rvm/gems/ruby-1.9.2-p180/gems/compass-0.11.1/lib/compass/installers/manifest.rb:112:in `each'
  /Users/dharmesh/.rvm/gems/ruby-1.9.2-p180/gems/compass-0.11.1/lib/compass/installers/manifest.rb:112:in`each'
  /Users/dharmesh/.rvm/gems/ruby-1.9.2-p180/gems/compass-0.11.1/lib/compass/installers/manifest_installer.rb:38:in `install'
  /Users/dharmesh/.rvm/gems/ruby-1.9.2-p180/gems/compass-0.11.1/lib/compass/installers/base.rb:33:in`run'
  /Users/dharmesh/.rvm/gems/ruby-1.9.2-p180/gems/compass-0.11.1/lib/compass/commands/stamp_pattern.rb:75:in `perform'
  /Users/dharmesh/.rvm/gems/ruby-1.9.2-p180/gems/compass-0.11.1/lib/compass/commands/base.rb:18:in`execute'
  /Users/dharmesh/.rvm/gems/ruby-1.9.2-p180/gems/compass-0.11.1/lib/compass/commands/project_base.rb:19:in `execute'
  /Users/dharmesh/.rvm/gems/ruby-1.9.2-p180/gems/compass-0.11.1/lib/compass/exec/sub_command_ui.rb:43:in`perform!'
  /Users/dharmesh/.rvm/gems/ruby-1.9.2-p180/gems/compass-0.11.1/lib/compass/exec/sub_command_ui.rb:15:in `run!'
  /Users/dharmesh/.rvm/gems/ruby-1.9.2-p180/gems/compass-0.11.1/bin/compass:25:in`block in <top (required)>'
  /Users/dharmesh/.rvm/gems/ruby-1.9.2-p180/gems/compass-0.11.1/bin/compass:39:in `call'
  /Users/dharmesh/.rvm/gems/ruby-1.9.2-p180/gems/compass-0.11.1/bin/compass:39:in`<top (required)>'
  /Users/dharmesh/.rvm/gems/ruby-1.9.2-p180/bin/compass:19:in `load'
  /Users/dharmesh/.rvm/gems/ruby-1.9.2-p180/bin/compass:19:in`<main>'

---

> gem list

**\* LOCAL GEMS ***

abstract (1.0.0)
actionmailer (3.0.7, 3.0.6)
actionpack (3.0.7, 3.0.6)
activemodel (3.0.7, 3.0.6)
activerecord (3.0.7, 3.0.6)
activeresource (3.0.7, 3.0.6)
activesupport (3.0.7, 3.0.6)
addressable (2.2.5)
arel (2.1.0, 2.0.9)
builder (3.0.0, 2.1.2)
bundler (1.0.12, 1.0.11)
chunky_png (1.1.1)
classifier (1.3.3)
coderay (0.9.8, 0.9.7)
coffee-script (2.2.0, 2.1.3)
coffee-script-source (1.1.0)
compass (0.11.1)
configuration (1.2.0)
crack (0.1.8)
daemons (1.1.3)
diff-lcs (1.1.2)
directory_watcher (1.4.0)
dotfiles (1.0.6)
em-files (0.2.2)
em-http-request (1.0.0.beta.3, 0.3.0)
em-socksify (0.1.0)
erubis (2.7.0, 2.6.6)
escape_utils (0.2.3)
eventmachine (1.0.0.beta.3, 0.12.10)
execjs (0.3.0)
fast-stemmer (1.0.0)
fattr (2.2.0)
fssm (0.2.7)
github (0.6.2)
growl (1.0.3)
haml (3.1.1, 3.0.25)
hash-utils (0.14.0)
highline (1.6.1, 1.5.2)
html5-boilerplate (0.3.3)
http_parser.rb (0.5.1)
http_router (0.7.5)
httparty (0.7.7)
i18n (0.5.0)
jekyll (0.10.0)
json (1.5.1)
json_pure (1.5.1)
launchy (0.4.0, 0.3.7)
less (1.2.21)
liquid (2.2.2)
mail (2.3.0, 2.2.17, 2.2.15)
maruku (0.6.0)
mechanize (1.0.0)
method_source (0.4.1)
middleman (1.2.4)
mime-types (1.16)
multi_json (1.0.0)
mutter (0.5.3)
narray (0.5.9.9)
nokogiri (1.4.4)
padrino-core (0.9.26)
padrino-helpers (0.9.26)
polyglot (0.3.1)
pry (0.8.3, 0.8.2)
pry-doc (0.2.1)
rack (1.2.2, 1.1.2)
rack-mount (0.7.2, 0.6.14)
rack-test (0.5.7)
radiant (0.9.1)
rails (3.0.7, 3.0.6)
railties (3.0.7, 3.0.6)
rake (0.8.7)
RedCloth (4.2.7)
rspec (2.5.0)
rspec-core (2.5.1)
rspec-expectations (2.5.0)
rspec-mocks (2.5.0)
ruby_parser (2.0.6)
rubygems-update (1.7.2)
sass (3.1.1)
session (3.1.0)
sexp_processor (3.0.5)
shotgun (0.9, 0.8)
sinatra (1.2.6)
slop (1.5.4, 1.5.3)
sqlite3 (1.3.3)
sqlite3-ruby (1.3.3, 1.3.2)
syntax (1.0.0)
text-format (1.0.0)
text-hyphen (1.0.0)
therubyracer (0.8.1)
thin (1.2.11)
thor (0.14.6)
tilt (1.3)
treetop (1.4.9)
tzinfo (0.3.27, 0.3.26)
uglifier (0.5.1)
url_mount (0.2.1)
wall-leecher (0.2.2, 0.2.1)
will_paginate (2.3.15)
yard (0.6.8)

**Comment by strass** [comment]
if you

```
mate /Library/Ruby/Gems/1.8/gems/html5-boilerplate-0.3.3/lib/../templates/project/index.html.haml
```

and add a comma into line 19:

```
%meta{ :name => "author", :content => "" }/
```

then it works.

**Comment by dmmalam** [comment]
thanks, any idea when this will be pushed into a new release, along with the compass 'single shadow to box-shadow is deprecated, warnings?

**Comment by strass** [comment]
No clue, unfortunately. I knew how to fix this since I had the same problem myself. Hopefully soon :)
