### ISSUE TITLE
Server fails to start in rails 2 app.

### ISSUE THREAD

**Issue by dza2000** [sporkd/compass-html5-boilerplate#17]
Everything was created fine and went great as I began the project, but when I tried to start the server, it vomited out this:

=> Rails 2.3.5 application starting on http://0.0.0.0:3001
C:/Ruby/lib/ruby/gems/1.8/gems/rails-2.3.5/lib/rails/gem_dependency.rb:119:Warning: Gem::Dependency#version_requirements is deprecated and will be removed on or after August 2010.  Use #requirement
C:/Ruby/lib/ruby/gems/1.8/gems/compass-0.11.1/lib/compass/compiler.rb:15:in `initialize': wrong number of arguments (1 for 0) (ArgumentError)
    from C:/Ruby/lib/ruby/gems/1.8/gems/compass-0.11.1/lib/compass/compiler.rb:15:in`new'
    from C:/Ruby/lib/ruby/gems/1.8/gems/compass-0.11.1/lib/compass/compiler.rb:15:in `initialize'
    from C:/Ruby/lib/ruby/gems/1.8/gems/compass-0.11.1/lib/compass/configuration/helpers.rb:146:in`new'
    from C:/Ruby/lib/ruby/gems/1.8/gems/compass-0.11.1/lib/compass/configuration/helpers.rb:146:in `compiler'
    from C:/Ruby/lib/ruby/gems/1.8/gems/compass-0.11.1/lib/compass/configuration/helpers.rb:140:in`handle_configuration_change!'
    from C:/Ruby/lib/ruby/gems/1.8/gems/compass-0.11.1/lib/compass/app_integration/rails.rb:61:in `initialize!'
    from C:/Users/dsullivan/Documents/Aptana Studio Workspace/cloner/config/initializers/compass.rb:3
    from C:/Ruby/lib/ruby/gems/1.8/gems/activesupport-2.3.5/lib/active_support/dependencies.rb:145:in`load_without_new_constant_marking'
    from C:/Ruby/lib/ruby/gems/1.8/gems/activesupport-2.3.5/lib/active_support/dependencies.rb:145:in `load'
    from C:/Ruby/lib/ruby/gems/1.8/gems/activesupport-2.3.5/lib/active_support/dependencies.rb:521:in`new_constants_in'
    from C:/Ruby/lib/ruby/gems/1.8/gems/activesupport-2.3.5/lib/active_support/dependencies.rb:145:in `load'
    from C:/Ruby/lib/ruby/gems/1.8/gems/rails-2.3.5/lib/initializer.rb:622:in`load_application_initializers'
    from C:/Ruby/lib/ruby/gems/1.8/gems/rails-2.3.5/lib/initializer.rb:621:in `each'
    from C:/Ruby/lib/ruby/gems/1.8/gems/rails-2.3.5/lib/initializer.rb:621:in`load_application_initializers'
    from C:/Ruby/lib/ruby/gems/1.8/gems/rails-2.3.5/lib/initializer.rb:176:in `process'
    from C:/Ruby/lib/ruby/gems/1.8/gems/rails-2.3.5/lib/initializer.rb:113:in`send'
    from C:/Ruby/lib/ruby/gems/1.8/gems/rails-2.3.5/lib/initializer.rb:113:in `run'
    from C:/Users/dsullivan/Documents/Aptana Studio Workspace/cloner/config/environment.rb:9
    from C:/Ruby/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in`gem_original_require'
    from C:/Ruby/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `require'
    from C:/Ruby/lib/ruby/gems/1.8/gems/activesupport-2.3.5/lib/active_support/dependencies.rb:156:in`require'
    from C:/Ruby/lib/ruby/gems/1.8/gems/activesupport-2.3.5/lib/active_support/dependencies.rb:521:in `new_constants_in'
    from C:/Ruby/lib/ruby/gems/1.8/gems/activesupport-2.3.5/lib/active_support/dependencies.rb:156:in`require'
    from C:/Ruby/lib/ruby/gems/1.8/gems/rails-2.3.5/lib/commands/server.rb:84
    from C:/Ruby/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `gem_original_require'
    from C:/Ruby/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in`require'
    from ./script/server:3
    from -e:2:in `load'
    from -e:2

Any ideas?

**Comment by sporkd** [comment]
Sorry. I had not planned on supporting Rails 2 .  But more importantly, if you're creating a new project as you say, then I can think of no good reason to not be using Rails 3.  You'll also have problems with lots of other libraries out there.

Hope this helps
