### ISSUE TITLE
undefined method `ie_html' in rspec controller tests

### ISSUE THREAD

**Issue by corydeppen** [sporkd/compass-html5-boilerplate#20]
I've created a simple Rails (3.0.7) app that uses rspec (2.5.0) and html5-boilerplate (1.0.0). When I visit a page it renders as expected, however if I run the default rspec controller tests they all fail with "undefined method `ie_html'". When I remove "render_views" from the controller spec the tests all pass. I'm not sure where the issue lies at this point. Any ideas?

**Comment by sporkd** [comment]
In your Gemfile, I am guessing you might be loading the html5-boilerplate in the development section.  It needs to be in the global section of your Gemfile because there are helper methods that need to be loaded for all environments.

**Comment by corydeppen** [comment]
I had it in the global section, but I noticed I had the html-boilerplate 0.3.3 gem installed as well. I also noticed Spork was still running. I uninstalled the older version of the boilerplate, restarted Spork, added the "render_views" back and all tests pass. I'm thinking the fact I hadn't restarted Spork may be the culprit.

**Comment by sporkd** [comment]
Yup, been there before as well.  Glad you got it working.
