### ISSUE TITLE
need keep up with html 5 boilerlate code? 

### ISSUE THREAD

**Issue by windhood** [sporkd/compass-html5-boilerplate#3]
boilerlate code has commits until 2010-10-13.
What is the best way to keep syn with the original code?

**Comment by sporkd** [comment]
I try to pull in the latest changes every week or so, but just haven't gotten to it this week.  However, there are only two commits you need, and neither require a new version of the gem to change on your own site.  Hope this helps.

http://github.com/paulirish/html5-boilerplate/commit/afaf14304e55dac23b2f4c38b6c5f67a7ddb70c8

http://github.com/paulirish/html5-boilerplate/commit/b87d0fbddfaa9437f6167b6a54ede42b17fff4e0

**Comment by windhood** [comment]
Thanks.

**Comment by andrewdeandrade** [comment]
Thanks for this making this compass extension.

FYI - I voted this up because there have been new commits to Paul Irish's code since this issue was submitted. The last commit by Paul Irish is Oct 26th.

**Comment by sporkd** [comment]
New version is out.  Sorry for the lag, it's been a busy month.

Peter

**Comment by arronmabrey** [comment]
I was going to fork and bring it up to date. Just wondering before I do if should sync with the current head or the latest stable version aka 2.0
